/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveNotesShow: typeof import('./src/components/ArchiveNotesShow.vue')['default']
    ArchiveRemindShow: typeof import('./src/components/ArchiveRemindShow.vue')['default']
    ArchiveTaskShow: typeof import('./src/components/ArchiveTaskShow.vue')['default']
    ChangePassword: typeof import('./src/components/ChangePassword.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FindNotesByTag: typeof import('./src/components/FindNotesByTag.vue')['default']
    FloatingButton: typeof import('./src/components/FloatingButton.vue')['default']
    NotesEdit: typeof import('./src/components/NotesEdit.vue')['default']
    NotesShow: typeof import('./src/components/NotesShow.vue')['default']
    RemindEdit: typeof import('./src/components/RemindEdit.vue')['default']
    RemindShow: typeof import('./src/components/RemindShow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagEdit: typeof import('./src/components/TagEdit.vue')['default']
    TaskEdit: typeof import('./src/components/TaskEdit.vue')['default']
    TaskShow: typeof import('./src/components/TaskShow.vue')['default']
    TrashNotesShow: typeof import('./src/components/TrashNotesShow.vue')['default']
    TrashRemindShow: typeof import('./src/components/TrashRemindShow.vue')['default']
    TrashTaskShow: typeof import('./src/components/TrashTaskShow.vue')['default']
    ValidCode: typeof import('./src/components/ValidCode.vue')['default']
  }
}
